### ISSUE TITLE
`ValueError` in `sigmoid` activation function `nanotorch.nn.functionnal`

### ISSUE THREAD

**Issue by JamorMoussa** [JamorMoussa/NanoTorch#13]
I'm just testing the `sigmoid` activation function, as shown in following code.
```python
from nanotorch.nn import functional as F

print(F.sigmoid(-10))
```

I got the following bug: 

```
➜  NanoTorch-DeepLearning-Library-From-Scratch git:(test-br) ✗ python3 sigmoid_test.py     
Traceback (most recent call last):
  File "/home/moussa/Documents/programming/NanoTorch-DeepLearning-Library-From-Scratch/sigmoid_test.py", line 5, in <module>
    print(F.sigmoid(-10))
          ^^^^^^^^^^^^^^
  File "/home/moussa/Documents/programming/NanoTorch-DeepLearning-Library-From-Scratch/nanotorch/nn/functional.py", line 12, in sigmoid
    return Tensor(1/(1 + np.exp(-input)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moussa/Documents/programming/NanoTorch-DeepLearning-Library-From-Scratch/nanotorch/tensor/tensor.py", line 38, in __new__
    raise ValueError(f"the 'input' attributes must be list, tuple, numpy.ndarray. But '{input.__class__.__name__}' is given") 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: the 'input' attributes must be list, tuple, numpy.ndarray. But 'float64' is given
```

I think the `Tensor` who raise the `ValueError`, it allows only `list`, `tuple`, `ndarray`, it not supports the `float64`.

Even we pass a list, to tuple :

```python
print(F.sigmoid([-10]))
``` 

we got the following Error: 

```
➜  NanoTorch-DeepLearning-Library-From-Scratch git:(test-br) ✗ python3 sigmoid_test.py
Traceback (most recent call last):
  File "/home/moussa/Documents/programming/NanoTorch-DeepLearning-Library-From-Scratch/sigmoid_test.py", line 4, in <module>
    print(F.sigmoid([-10]))
          ^^^^^^^^^^^^^^^^
  File "/home/moussa/Documents/programming/NanoTorch-DeepLearning-Library-From-Scratch/nanotorch/nn/functional.py", line 12, in sigmoid
    return Tensor(1/(1 + np.exp(-input)))
                                ^^^^^^
TypeError: bad operand type for unary -: 'list'
```

**Comment by JamorMoussa** [comment]
I think we need to check for dtype of `input`.
